/* eslint-disable no-unused-vars */
// eslint-disable-next-line no-unused-vars
import React, { useState, useEffect } from "react";
import { IconUser, IconShieldCheck } from "@tabler/icons-react";
import {
  Avatar,
  Tabs,
  Box,
  Select,
  Tooltip,
  TextInput,
  Text,
} from "@mantine/core";
import { DataTable } from "mantine-datatable";
import "mantine-datatable/styles.layer.css";
import { getUserAccounts } from "./../ItemsAxios";
import { notifications } from "@mantine/notifications";
import { IconUserCheck } from "@tabler/icons-react";
import { IconUserOff } from "@tabler/icons-react";
import { IconBan } from "@tabler/icons-react";
import { IconPlus } from "@tabler/icons-react";
import { IconUserPlus } from "@tabler/icons-react";
import { IconCalendar } from "@tabler/icons-react";
import { useDisclosure } from "@mantine/hooks";
import { Modal, Button, Radio, Group } from "@mantine/core";
import axios from "axios";
import { IconAlertTriangle } from "@tabler/icons-react";
import { modals } from "@mantine/modals";

// import { eachDayOfInterval } from "date-fns";

function successNotif(message) {
  notifications.show({
    title: "Success",
    message: message,
    color: "green",
  });
}

function errorNotif(message) {
  notifications.show({
    title: "Error",
    message: message,
    color: "red",
  });
}

const openModal = (id, value) =>
  modals.openConfirmModal({
    title: "Please confirm your action",
    children: (
      <Text size="sm">
        Proceed <span>{value ? "enabling" : "disabling"}</span> this account?
      </Text>
    ),
    labels: { confirm: "Confirm", cancel: "Cancel" },
    onCancel: () => console.log("Cancel"),
    onConfirm: async () => {
      console.log(id, typeof id, value);
      try {
        const res = await axios.put(
          "http://localhost:8080/admin-enableAccount",
          null,
          {
            params: {
              userId: id,
              value: value,
            },
            withCredentials: true,
          }
        );
        successNotif("User updated");
      } catch (err) {
        errorNotif(err.response?.data);
        console.log(err.response);
      }
    },
  });

function handleToggleAccount(id, value) {
  openModal(id, value);
}

const AddUserForm = ({ opened, close }) => {
  const [access, setAccess] = useState("PLANNER");
  const [fname, setFname] = useState("");
  const [lname, setLname] = useState("");
  const [email, setEmail] = useState("");
  const [response, setResponse] = useState({});

  const handleAddUser = async (e) => {
    e.preventDefault();
    const requestData = {
      firstname: fname,
      lastname: lname,
      role: access,
      email: email,
    };

    try {
      const res = await axios.post(
        "http://localhost:8080/admin-addUser",
        requestData,
        {
          withCredentials: true,
        }
      );
      setResponse(res.data);
      console.log(res.data); // safe to use here
      successNotif("user added!");
    } catch (err) {
      errorNotif(err.response?.data);
    }
  };

  return (
    <>
      <Modal
        opened={opened}
        onClose={() => {
          setResponse();
          setAccess("");
          setFname("");
          setLname("");
          setEmail("");
          close();
        }}
        title="Add user"
        size={"lg"}
      >
        <form onSubmit={handleAddUser}>
          <p className="text-gray-600">
            Password will be autogenerated. User needs to verify their email
            account using email (username) and password.
          </p>
          <div className="py-2">
            <div className="grid grid-cols-2 gap-4">
              <TextInput
                label="firstname"
                value={fname}
                onChange={(event) => setFname(event.currentTarget.value)}
              ></TextInput>
              <TextInput
                label="lastname"
                value={lname}
                onChange={(event) => setLname(event.currentTarget.value)}
              ></TextInput>
            </div>
            <div className="grid grid-cols-3 mb-4">
              <TextInput
                label="email"
                className="col-span-2"
                type="email"
                value={email}
                onChange={(event) => setEmail(event.currentTarget.value)}
              ></TextInput>
            </div>
            <Radio.Group
              name="Access"
              label="Access"
              description="This will be the role access of the created account"
              value={access}
              onChange={setAccess}
              className="pb-4"
            >
              <Group mt="xs">
                <Radio value="CUSTOMER" label="customer" />
                <Radio value="PLANNER" label="planner" />
                <Radio value="ADMIN" label="admin" />
              </Group>
            </Radio.Group>
            <Button type="submit">submit</Button>
          </div>
        </form>
        {response && (
          <>
            <div className="py-2">
              <span className="font-semibold text-green-500">
                record saved!
              </span>
            </div>
            <div className="grid grid-cols-2 border border-gray-300 px-5 py- 5">
              <ul className="list-none py-2">
                <li>Full name</li>
                <li>Email</li>
                <li>Role</li>
                <li>Password</li>
              </ul>
              <ul className="list-none py-2 font-semibold">
                <li>
                  {response.firstname} {response.lastname}
                </li>
                <li>{response.email}</li>
                <li>{response.access}</li>
                <li>{response.password}</li>
              </ul>
            </div>
            <div className="flex justify-center pt-4">
              <Button
                onClick={() => {
                  setResponse();
                  setAccess("");
                  setFname("");
                  setLname("");
                  setEmail("");
                  close();
                }}
              >
                close
              </Button>
            </div>
          </>
        )}
      </Modal>
    </>
  );
};

const UserRoleManager = () => {
  const [activeTab, setActiveTab] = useState("all");
  const [userAccounts, setUserAccounts] = useState([]);
  const [pageNumber, setPageNumber] = useState(1);
  const [totalElements, setTotalElements] = useState(0);
  const [pageIsLast, setPageIsLast] = useState(false);

  const [loading, setLoading] = useState(false);
  const [opened, { open, close }] = useDisclosure(false);

  useEffect(() => {
    const filter = activeTab === "all" ? null : activeTab;
    setLoading(true);
    getUserAccounts({ filter, pageNumber })
      .then((res) => {
        setUserAccounts(res?.data?.content);
        setTotalElements(res?.data?.totalElements);
        setPageIsLast(res?.data?.last);
      })
      .catch(console.log)
      .finally(() => setLoading(false));
  }, [activeTab, pageNumber]);

  const MyDataTable = () => (
    <>
      <DataTable
        columns={[
          {
            accessor: "Account",
            render: (row) => (
              <Box className="flex items-center gap-2">
                <Avatar
                  src={
                    row.avatarUrl?.trim()
                      ? row.avatarUrl
                      : "https://i.pravatar.cc/150?img=5"
                  }
                />
                <span>
                  {row.firstName} {row.lastName}
                </span>
              </Box>
            ),
          },
          {
            accessor: "Email",
            render: (row) => (
              <Box className="flex items-center  gap-2">
                {row.emailVerified === true ? (
                  <IconShieldCheck size={16} color="green" />
                ) : (
                  <Tooltip label="email not yet verified" color="red">
                    <IconAlertTriangle
                      size={16}
                      color="orange"
                    ></IconAlertTriangle>
                  </Tooltip>
                )}

                {row.email}
              </Box>
            ),
          },
          {
            accessor: "Joined Since",
            render: (row) => (
              <Box className="flex items-center  gap-2">
                <IconCalendar size={16} color="gray" />
                {row.dateAdded}
              </Box>
            ),
          },
          {
            accessor: "Role",
            render: (row) => (
              <Box className="flex items-center  gap-2">
                <Select
                  data={[
                    { value: "ADMIN", label: "Admin" },
                    { value: "PLANNER", label: "Planner" },
                    { value: "CUSTOMER", label: "Customer" },
                  ]}
                  value={row.role}
                  readOnly
                  // onChange={(newRole) => handleRoleChange(newRole, row.id)}
                  size="xs"
                  variant="filled"
                  className="w-[130px] outline-none"
                />
              </Box>
            ),
          },
          {
            accessor: "Status",
            render: (row) => (
              <Box className="flex items-center  gap-2">
                <span>
                  {row.enabled === true ? (
                    <Tooltip label="active" color="gray">
                      <IconUserCheck color="gray" size={20}></IconUserCheck>
                    </Tooltip>
                  ) : (
                    <Tooltip label="inactive">
                      <IconUserOff color="gray" size={20}></IconUserOff>
                    </Tooltip>
                  )}
                </span>
              </Box>
            ),
          },
          {
            accessor: "Access",
            render: (row) => (
              <Box className="flex items-center  gap-2">
                <span>{row.role === "ADMIN" ? "Full" : "Partial"}</span>
              </Box>
            ),
          },
          {
            accessor: "account",
            title: "Account",
            render: (row) => (
              <div className="flex items-center gap-2">
                {row.enabled ? (
                  <Button
                    variant=""
                    color="red"
                    onClick={() => {
                      const value = false;
                      const id = row.id;
                      handleToggleAccount(id, value);
                    }}
                  >
                    disable
                  </Button>
                ) : (
                  <Button
                    variant=""
                    color="green"
                    onClick={() => {
                      const value = true;
                      const id = row.id;
                      handleToggleAccount(id, value);
                    }}
                  >
                    enable
                  </Button>
                )}
              </div>
            ),
          },
        ]}
        loading={loading}
        page={pageNumber}
        onPageChange={setPageNumber}
        records={userAccounts}
        paginationSize="md"
        paginationActiveBackgroundColor="grape"
        noRecordsText="no record found"
        minHeight={300}
        recordsPerPage={10}
        paginationprops={{
          nextDisabled: pageIsLast,
          previousDisabled: pageNumber <= 1,
        }}
        totalRecords={totalElements}
        paginationText={({ from, to, totalRecords }) =>
          `Showing users ${from} to ${to} out of ${totalRecords} record/s`
        }
      ></DataTable>
    </>
  );

  return (
    <div className=" py-10 border border-gray-300 mx-auto px-[30px] bg-white pb-10">
      <div className="border border-gray-300 rounded">
        <div className="info py-5 px-5 ">
          <p className="text-gray-800 font-semibold">User accounts</p>
          <p className="text-gray-900 text-[14px] mb-5">
            Find all user accounts and their associated roles.
          </p>
          <div className="user-table min-h-[50vh]">
            <Tabs defaultValue="all" onChange={setActiveTab}>
              <Tabs.List>
                <Tabs.Tab value="all">All</Tabs.Tab>
                <Tabs.Tab value="ADMIN">Admin</Tabs.Tab>
                <Tabs.Tab value="PLANNER">Planner</Tabs.Tab>
                <Tabs.Tab value="CUSTOMER">Client</Tabs.Tab>
                <Tooltip label="add user">
                  <button
                    className="ml-auto flex items-center mb-1 rounded-2xl px-2 bg-blue-500 hover:bg-blue-400"
                    onClick={open}
                  >
                    <IconUserPlus color="white" size={14}></IconUserPlus>
                    {/* <span className="text-white">planner</span> */}
                  </button>
                </Tooltip>
              </Tabs.List>
              <Tabs.Panel value={activeTab}>
                <MyDataTable />
              </Tabs.Panel>
            </Tabs>
          </div>
          <AddUserForm opened={opened} close={close}></AddUserForm>
        </div>
      </div>
    </div>
  );
};

export default UserRoleManager;
